### ISSUE TITLE
[Q] TS Frame Complete info

### ISSUE THREAD

**Issue by kkhatr2** [guozhaohui/TSParser#3]
Hi @guozhaohui 

Thank you for writing this tool in python!

I am analyzing some TS files with your `TSParser` and `tsduck` and `ffprobe`. 
`ffprobe -show_frames -i /input/file` shows information including `pict_type` = I-frame, B-frame, P-frame and `pkt_size`, `pts`, `dts`, etc, I believe because of `-show_frames` command the `pkt_size` is the frame size in Kilo-bytes.

The information that `ffprobe` gathers about the frame is contained in the ts-packet's headers somewhere, and I wanted some help in getting this information, specifically so that I can pin down exactly at what ts-packet number does a frame form.

Any help will be greatly appreciated.

**Comment by guozhaohui** [comment]
Hi, @kkhatr2
If my memory serve me correctly, The pict_type, i.e. I/B/P frame, is stored in the element stream, and the information format also depends on the type of element steam. So you should not stop at the TS steam parsing by TSParser, and improve this script to parse the element stream to retrieve the pict_type information you want.

**Comment by kkhatr2** [comment]
One of my goals is to compare the results from these different tools and then adjust this script. 

So, I can definitely add my thoughts to extend this script.  If you have references to the schema for the different header fields that I can use to add more functionality, that will be great.  

The stream I have contains 1 program with multiplexed 1 aac audio track and 1 MPEG2-video encoded with H.264, it also has tons of empty packets which were included to maintain the bit-rate.

I found this http://dvd.sourceforge.net/dvdinfo/mpeghdrs.html reference, but am not sure if it is entirely correct because, it does not mention that the stream should start with the sync byte, although at the top the author does mention that this is work in progress.

**Comment by guozhaohui** [comment]
Because there are too many types of element stream and they all have different format, so I shared this script stopped at the TS level parsing.  To add support for certain ES type, you have to extend this script by yourself, this is just what I have done. For the format of ES stream, you need to refer its specification document. 

In the parseIndividualPESPayload() function, IDR_picture field was checked, by which you can find a good start point for ES stream, I think you can dump the ES stream packet payload data to a new file and parsing it with specific script to fit the ES type.

**Comment by guozhaohui** [comment]
Because no further questions, I closed this issue.
